all:
	@make -C ipodclassic-default
	@make -C ipodclassic-default-fastboot
	@make -C ipodnano2g-default
	@make -C ipodnano2g-default-fastboot

clean:
	@make -C ipodclassic-default clean
	@make -C ipodclassic-default-fastboot clean
	@make -C ipodnano2g-default clean
	@make -C ipodnano2g-default-fastboot clean

.PHONY: all clean
